# Generated by Django 6.0.3 on 2026-05-15 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postimage',
            name='compressed_image',
            field=models.ImageField(null=True, upload_to='compressed_image/'),
        ),
        migrations.AlterField(
            model_name='postimage',
            name='original_image',
            field=models.ImageField(null=True, upload_to='original_image/'),
        ),
    ]
