# Generated by Django 6.0.3 on 2026-05-26 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post_app', '0002_alter_postimage_compressed_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postimage',
            name='compressed_image',
            field=models.ImageField(null=True, upload_to='post_app/compressed_image/'),
        ),
        migrations.AlterField(
            model_name='postimage',
            name='original_image',
            field=models.ImageField(null=True, upload_to='post_app/original_image/'),
        ),
    ]
